name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v3

    - name: Inject API key into gradle.properties
      run: echo "AIRCRAFT_API_KEY=${{ secrets.AIRCRAFT_API_KEY }}" >> ~/.gradle/gradle.properties

- name: Download, unzip OpenCV SDK and list folders
  run: |
    wget -q --show-progress https://github.com/opencv/opencv/releases/download/4.11.0/opencv-4.11.0-android-sdk.zip
    unzip -q opencv-4.11.0-android-sdk.zip
    mkdir -p openCVLibrary
    cp -r OpenCV-android-sdk/sdk/java/* openCVLibrary/
    mkdir -p app/opencv
    cp -r OpenCV-android-sdk/sdk/* app/opencv/
    echo "Top-level folders after copy:"
    echo "openCVLibrary:"
    ls -1 openCVLibrary
    echo "app/opencv:"
    ls -1 app/opencv



    - name: Make gradlew executable
      run: chmod +x gradlew

    - name: Build Android app
      run: ./gradlew assembleDebug
