name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v3

    - name: Inject API key into gradle.properties
      run: echo "AIRCRAFT_API_KEY=${{ secrets.AIRCRAFT_API_KEY }}" >> ~/.gradle/gradle.properties

    - name: Build Android app
      run: ./gradlew assembleDebug
